apiVersion: v2
appVersion: 0.13.0
description: Set of components that automatically adjust the amount of CPU and memory requested by pods running in the Kubernetes Cluster
home: https://github.com/kubernetes/autoscaler
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: vertical-pod-autoscaler
sources:
  - https://github.com/kubernetes/autoscaler
  - https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler
version: 6.1.0-bb.1
dependencies:
  - name: common
    version: 1.16.1
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.22"
  helm.sh/images: |
    - name: recommender
      image: registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler/recommender:0.13.0
    - name: kubectl
      image: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.26.1
    - name: admission-controller
      condition: admissionController.enabled
      image: registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler/admission-controller:0.13.0
    - name: updater
      condition: updater.enabled
      image: registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler/updater:0.13.0
    - name: pytest
      condition: tests.enabled
      image: ghcr.io/cowboysysop/pytest:1.0.35

