apiVersion: v2
name: vertical-pod-autoscaler
description: Set of components that automatically adjust the amount of CPU and memory requested by pods running in the Kubernetes Cluster
version: 9.8.1-bb.0
appVersion: 1.1.1
home: https://github.com/kubernetes/autoscaler
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
sources:
  - https://github.com/kubernetes/autoscaler
  - https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler
dependencies:
  - name: common
    version: 1.16.1
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  bigbang.dev/applicationVersions: |
    - Recommender: 1.1.1
    - Admission-Controller: 1.1.1
  kubeVersion: ">=1.22"
  helm.sh/images: |
    - name: recommender
      image: registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler/recommender:1.1.1
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
    - name: admission-controller
      condition: admissionController.enabled
      image: registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler/admission-controller:1.1.1
    - name: updater
      condition: updater.enabled
      image: registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler/updater:1.1.1
    - name: pytest
      condition: tests.enabled
      image: ghcr.io/cowboysysop/pytest:1.0.38

